include:
  - file: "/build/java/template-java-gradle.yml"
    project: "platform/pipelines-templates"
    ref: "master"
  - project: 'mia-platform/pipelines-templates'
    file: '/common/docker-build-branch.yml'
    ref: master

default:
  image: eclipse-temurin:17.0.10_7-jdk-jammy

variables:
  IMAGE_NAME: crud-sql-template

build-jar:
  script:
    - ./gradlew clean build
    - ./gradlew shadowJar
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

build-branch:
  rules:
    - if: '$CI_COMMIT_TAG =~ "/^$/" && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'