include:
  - file: "/build/java/template-java-gradle.yml"
    project: "platform/pipelines-templates"
    ref: "master"
  - file: "/build/java/template-java-gradle-test-latest.yml"
    project: "platform/pipelines-templates"
    ref: "master"

default:
  image: eclipse-temurin:17.0.10_7-jdk-jammy

variables:
  IMAGE_NAME: crud-sql-template
